apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inf-backend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: team-troy
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/kcoleman731/argo-apps
    path: team-troy
    targetRevision: {{ .Values.spec.source.targetRevision }}
