apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-burnham-workload
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: team-burnham
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: ssh://git@github.com:kcoleman731/argo-apps.git
    path: team-burnham
    targetRevision: {{ .Values.spec.source.targetRevision }}
